begin;

INSERT INTO genres (genre_name) VALUES
                               ('Action'),
                               ('Adventure'),
                               ('Role-Playing Game (RPG)'),
                               ('Strategy'),
                               ('Simulation'),
                               ('Sports'),
                               ('Fighting'),
                               ('Shooter'),
                               ('Platformer'),
                               ('Puzzle'),
                               ('Racing'),
                               ('Stealth'),
                               ('Survival'),
                               ('Horror'),
                               ('MMORPG (Massively Multiplayer Online Role-Playing Game)'),
                               ('MOBA (Multiplayer Online Battle Arena)'),
                               ('Rhythm'),
                               ('Visual Novel'),
                               ('Educational'),
                               ('Idle/Incremental'),
                               ('Interactive Fiction'),
                               ('Artillery'),
                               ('Roguelike'),
                               ('Open World'),
                               ('City Building'),
                               ('Management'),
                               ('Card Game'),
                               ('Tower Defense'),
                               ('Beat them Up'),
                               ('Hack and Slash'),
                               ('Party Game'),
                               ('Dating Simulator'),
                               ('Escape Room'),
                               ('Sandbox'),
                               ('Real-Time Strategy (RTS)'),
                               ('Turn-Based Strategy (TBS)'),
                               ('Turn-Based Tactics'),
                               ('Tactical Shooter'),
                               ('First-Person Shooter (FPS)'),
                               ('Third-Person Shooter (TPS)'),
                               ('Narrative'),
                               ('Science Fiction (Sci-Fi)'),
                               ('Fantasy'),
                               ('Steampunk'),
                               ('Cyberpunk'),
                               ('Western'),
                               ('Historical'),
                               ('Military'),
                               ('Espionage'),
                               ('Mystery'),
                               ('Detective'),
                               ('Crime'),
                               ('Superhero'),
                               ('Post-Apocalyptic'),
                               ('Space'),
                               ('Alien'),
                               ('Zombie'),
                               ('Vampire'),
                               ('Ninja'),
                               ('Samurai'),
                               ('Martial Arts'),
                               ('Stealth Action'),
                               ('Exploration'),
                               ('Trading'),
                               ('Naval'),
                               ('Flight Simulation'),
                               ('Driving Simulation'),
                               ('Motorcycle Racing'),
                               ('Extreme Sports'),
                               ('Snowboarding'),
                               ('Skateboarding'),
                               ('Fishing'),
                               ('Hunting'),
                               ('Cycling'),
                               ('War'),
                               ('Historical Battle'),
                               ('Medieval'),
                               ('Mythology'),
                               ('Gothic'),
                               ('Pirates'),
                               ('Survival Horror'),
                               ('Psychological Horror'),
                               ('Action-Adventure'),
                               ('Metroidvania'),
                               ('Art Game'),
                               ('Walking Simulator'),
                               ('Time Management'),
                               ('Life Simulation'),
                               ('God Game'),
                               ('Construction and Management Simulation'),
                               ('Pet Simulation'),
                               ('Creature Collector'),
                               ('Trading Card Game (TCG)'),
                               ('Digital Collectible Card Game (CCG)'),
                               ('Real-Time Card Game (RTCG)'),
                               ('Music/Rhythm Game');

commit;
