package pt.isel.ls.utils

import kotlin.random.Random

/**
 * Generates a random email address.
 *
 * The email address is generated by concatenating a random string before the '@' symbol
 * with another random string after the '@' symbol and appending '.com' at the end.
 *
 * @return A randomly generated email address.
 */
fun generateRandomEmail(): String = "${generateRandomString()}@${generateRandomString()}.com"

/**
 * Generates a random string of characters.
 *
 * The string length is randomly chosen between 5 and 15 characters.
 * The characters in the string are selected from the English alphabet (both lowercase and uppercase).
 *
 * @return A randomly generated string.
 */
fun generateRandomString(): String {
    // Define the characters allowed in the random string
    val allowedChars = ('a'..'z') + ('A'..'Z')
    // Generate a list of random characters with a random length between 5 and 15
    return List(Random.nextInt(5, 16)) { allowedChars.random() }.joinToString("")
}
