name: Java Gradle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Corretto JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -O https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
          sudo tar xvf amazon-corretto-17-x64-linux-jdk.tar.gz -C /usr/lib/jvm/
          export JAVA_HOME=/usr/lib/jvm/amazon-corretto-17
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run Tests
        run: ./gradlew test
